### ISSUE TITLE
Structure, interaction and use of a IDS Vocabulary Hub

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDS-RAM_4_0#200]
---
name: Epic
about: Describe rationale and need for a change as an epic
title: Structure, interaction and use of a IDS Vocabualry Hub
labels: documentation, enhancement

---

## Rationale ##

As a data space participant, I want to use reusable semantic models (ontologies) to share and consume data in a data space to achieve semantic interoperability in an IDS data space. 

## Owner ##

@ssteinbuss 
@anilturkmayali 

## Stakeholder Point of Contact ##

@ssteinbuss 
@anilturkmayali 

## Dependencies ##

* Vocabularies should be linked to the IDS Infomodel
* A component shall be based on the IDS RAM concepts (Vocabualry Hub)
* Communication shall be in relation to the communication scheme in IDS-G
* Certification of a Vocabulary Hub shall be based on the IDS Certification

## Description ##

The interoperability requirements in the IDS directly lead to the usage of commonly known, standardized terms to describe data, services, contracts, and so on. Collection of these standardized identifiers form so-called vocabularies. In the most basic appearance, any list of controlled terms can be a vocabulary. To make use of their content, the respective vocabulary documents need to be shared between the relevant parties. This can be done through digital catalogs but also in printed forms like for instance a language dictionary.
In the IDS, however, further requirements occur. The terms of the vocabulary must be machine-readable, also to some degree their descriptions and titles, as well as new terms must be available for lookups. As stated in [Section 3.4](https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/blob/main/documentation/3_Layers_of_the_Reference_Architecture_Model/3_4_Information_Layer/README.md), the IDS relies in RDF to encode its attributes and data descriptions. The IDS Information Model is the central vocabulary that all parties of any IDS share.

## Context ##

* Semantic Interoperability in IDS Data Spaces

## Issues ##

- [ ]  #205 
- [ ] #206 
- [ ] #210 
- [ ] #207 
- [ ] #208 
- [ ] #209 
- [ ] #222 

## Acceptance criteria ##

to be defined

## Proof ##

to be defined

**Comment by WvandenBerg** [comment]
Please see review my pull requests #231 which is an attempt to fulfill #205
