### ISSUE TITLE
Vocabulary Hub in Section 3.1 Business Layer: review and update 

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDS-RAM_4_0#206]
A review of section 3.1 Business Layer would be required to check if any update is required based on the current Vocabulary Hub Workshop series. 
- [Roles](https://docs.internationaldataspaces.org/ids-ram-4/layers-of-the-reference-architecture-model/3-layers-of-the-reference-architecture-model/3-1-business-layer/3_1_1_roles_in_the_ids)
- [Interactions](https://docs.internationaldataspaces.org/ids-ram-4/layers-of-the-reference-architecture-model/3-layers-of-the-reference-architecture-model/3-1-business-layer/3_1_1_roles_in_the_ids)

**Comment by ssteinbuss** [comment]
The section on [Interactions in the Business Layer](https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/blob/206-vocabulary-hub-in-section-31-business-layer-review-and-update/documentation/3_Layers_of_the_Reference_Architecture_Model/3_1_Business_Layer/3_1_2_Interaction_of_Roles.md) consists of the role model graphic and the interaction table.

- the graphics need an update. There is currently no link between the data provider and the Vocabulary Hub. This should be added. But at the moment it is still unclear how this arrow can be labeled. 
- The following interactions are described in the table and should be explained in the document somewhere (establish a link between the cell and the section)
  - Data Owner (optional):
  - Data Provider (optional):
  - Data Consumer (optional):
  - Data User (optional):
  - Broker (unknown): 
  - Clearing House (optional):
  - Identity Provider (optional):
  - Service Provider (optional):
  - Vocabulary Provider (none):
  - App Store (optional)
  - Certification Body (none):
  - Evaluation Facility (mandatory):
  - App Provider (optional):

ToDo:

- [ ] Update graphic with an arrow between Vocabulary Hub and Data Provider
- [ ] Label the arrow mentioned above. 
- [ ] The table uses the term Vocabulary Provider shall this be renamed to Vocabulary  Hub?

**Comment by Krieke** [comment]
@ssteinbuss can it be that the graph [Interactions in the Business Layer](https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/blob/206-vocabulary-hub-in-section-31-business-layer-review-and-update/documentation/3_Layers_of_the_Reference_Architecture_Model/3_1_Business_Layer/3_1_2_Interaction_of_Roles.md) contains an issue?

The arrow information between the `Data Provider` and the `Broker Service Provider` has a caption `search metadata`.  Based on my understanding (is pretty fresh) I thought it would be `publish metadata`.  Can it be that the captions for the arrows between the `Broker Service Provider` and `Data Provider` and between  the `Broker Service Provider` and `Data Consumer` should be swapped?

**Comment by ssteinbuss** [comment]
> @ssteinbuss can it be that the graph [Interactions in the Business Layer](https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/blob/206-vocabulary-hub-in-section-31-business-layer-review-and-update/documentation/3_Layers_of_the_Reference_Architecture_Model/3_1_Business_Layer/3_1_2_Interaction_of_Roles.md) contains an issue?
> 
> The arrow information between the `Data Provider` and the `Broker Service Provider` has a caption `search metadata`. Based on my understanding (is pretty fresh) I thought it would be `publish metadata`. Can it be that the captions for the arrows between the `Broker Service Provider` and `Data Provider` and between the `Broker Service Provider` and `Data Consumer` should be swapped?

Yes, addressed in #225

**Comment by ssteinbuss** [comment]
I will create the links from the tables to the section, when we have merged the new text to avoid broken links
