### ISSUE TITLE
Vocabularies in section 3.3 Information Layer

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDS-RAM_4_0#207]
The Vocabularies were removed from the Information Layer, but we should describe the linkage and use of Vocabularies there, too. 

We should discuss.
[Information Layer](https://docs.internationaldataspaces.org/ids-ram-4/layers-of-the-reference-architecture-model/3-layers-of-the-reference-architecture-model/3_3_informationlayer)[://docs.internationaldataspaces.org/ids-ram-4/layers-of-the-reference-architecture-model/3-layers-of-the-reference-architecture-model/3_3_informationlayer](https://docs.internationaldataspaces.org/ids-ram-4/layers-of-the-reference-architecture-model/3-layers-of-the-reference-architecture-model/3_3_informationlayer)

**Comment by clange** [comment]
@ssteinbuss @jlangkau done via these commits to https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/tree/200-structure-interaction-and-use-of-a-ids-vocabulary-hub:
[Diff](https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/compare/0eb97450ea127ba851cb16462bcd437ee5778541..191293055d26396fb3908d69eec2a54e5cf21e7f) (just check the first file)
