### ISSUE TITLE
Broker: Predefine Data Categories and other mandatory fields for specific data spaces

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-RAM_4_0#25]
Hi,

In the DRM we discussed about predefining which data categories and other important fields have to be filled by the connector for a specific data space. And especially which selection there is, so that there is as harmonious a data category overview as possible. 

For this, the connector will have to query what the broker expects and then define this as a default for the user. The broker itself needs a possibility, over which the template is predefined.

Side thought: How does a solution work with a broker serving multiple Data spaces?

@HeinrichPet @sebbader @HaydarAk @clange 

Best regards,
Heinrich

**Comment by sebbader** [comment]
I wouldn't allow dummy placeholders like "not available" as then the any mandatory field can be missed. In addition, putting the responsibility for complete self-descriptions to the Metadata Broker makes it nearly impossible to have correct content. Only the source connector knows himself, and only he is allowed to tell the world about him.

**Comment by sebbader-sap** [comment]
I think this discussion has let to no result and the ticket can be closed. @JessicaRombs

**Comment by HeinrichPet** [comment]
@sebbader-sap Oh, I think it somehow does, see DSSD here: https://docs.internationaldataspaces.org/idsa-rulebook-v2/idsa-rulebook/3_functional_requirements#attributes-and-self-descriptions This has to been adressed technical in a newer RAM version, so that Rulebook and RAM ist aligned again.
