### ISSUE TITLE
Sources of Pictures

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/IDS-RAM_4_0#75]
The rendered pictures are in the respective folders (e.g. https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/tree/creating_new_structure/documentation/media) but the sources (visio or drawio?) are missing. Let's also share them, so every contributor can do adjustments directly. 

For instance, @chquix and @Jaro (anyone has his Github account?), can you please upload your files?

**Comment by ssteinbuss** [comment]
Closed by #193
