### ISSUE TITLE
Definition of participant identity

### ISSUE THREAD

**Issue by gbrost** [International-Data-Spaces-Association/IDS-RAM_4_0#77]
Multiple issues and discussions lead to the need for a well-defined participant identity. 
This is the baseline for Data Provenance, UC policies, connector deployment, self-descriptions. 
We need participant certificates, maybe based on roles. Key usage could be:
- Sign policies
- Sign self-descriptions
- Act on behalf on participant business entity

**Comment by ssteinbuss** [comment]
Closed by #193
