### ISSUE TITLE
Defining or Removing the Update Repository

### ISSUE THREAD

**Issue by sebbader** [International-Data-Spaces-Association/IDS-RAM_4_0#78]
The System Layer speaks about an 'Update Repository' (https://github.com/International-Data-Spaces-Association/IDS-RAM_4_0/blob/3703bb0b7e6c60d47343bc866197f8a4fa8d245a/documentation/3_Layers_of_the_Reference_Architecture_Model/3_5_System_Layer/3_5_0_System_Layer.md?plain=1#L23), who is responsible for it and defines it? Or shall we dismiss it completely?

**Comment by ssteinbuss** [comment]
Both were removed in the meanwhile. Therefore closing this issue
